import type { LucideIcon } from "lucide-react";
import {
  Braces,
  FileText,
  Clock,
  Hash,
  KeyRound,
  Link2,
  Palette,
  QrCode,
  Type,
  Binary,
  Fingerprint,
  Search,
  Code2,
  Tag,
  BarChart3,
  ArrowDownAZ,
  Calculator,
  Table2,
  Diff,
  Key,
  Boxes,
  Globe,
  Contrast,
  FileCode2,
  FileCode,
  Database,
  FileType,
  Brackets,
  Terminal,
  CalendarClock,
  Network,
  Filter,
  Image as ImageIcon,
  Wind,
  Layers,
  Square,
  Dice5,
  ShieldCheck,
  Quote,
  ListChecks,
  Workflow,
  TableProperties,
  Shapes,
  Paintbrush,
  Globe2,
  FileCheck,
  HardDrive,
  Lock,
  FileJson,
  Shield,
  GitBranch,
  FileX,
  Link,
  CalendarDays,
  Ruler,
} from "lucide-react";

export type ToolCategory =
  | "converter"
  | "encoder"
  | "generator"
  | "text"
  | "time"
  | "web"
  | "color"
  | "crypto";

export interface Tool {
  slug: string;
  name: string;
  description: string;
  category: ToolCategory;
  icon: LucideIcon;
  keywords: string[];
  featured?: boolean;
}

export interface CategoryMeta {
  id: ToolCategory;
  label: string;
  description: string;
}

export const categories: CategoryMeta[] = [
  { id: "converter", label: "Converter", description: "Convert between formats and units" },
  { id: "encoder", label: "Encoder", description: "Encode, decode, and transform data" },
  { id: "generator", label: "Generator", description: "Generate IDs, codes, and mock data" },
  { id: "text", label: "Text", description: "Manipulate and analyze text" },
  { id: "time", label: "Time", description: "Work with timestamps and dates" },
  { id: "web", label: "Web", description: "Tools for the web" },
  { id: "color", label: "Color", description: "Pick, convert, and explore colors" },
  { id: "crypto", label: "Crypto", description: "Hashes and cryptographic primitives" },
];

export const tools: Tool[] = [
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Format, minify, and validate JSON instantly in your browser.",
    category: "converter",
    icon: Braces,
    keywords: ["json", "format", "pretty", "minify", "validate", "lint"],
    featured: true,
  },
  {
    slug: "base64",
    name: "Base64 Encode/Decode",
    description: "Convert text to and from Base64 with one click.",
    category: "encoder",
    icon: Binary,
    keywords: ["base64", "encode", "decode", "atob", "btoa"],
    featured: true,
  },
  {
    slug: "unix-timestamp",
    name: "Unix Timestamp Converter",
    description: "Convert between Unix timestamps and human-readable dates.",
    category: "time",
    icon: Clock,
    keywords: ["unix", "timestamp", "epoch", "date", "iso", "time"],
    featured: true,
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate UUID v4 identifiers in bulk.",
    category: "generator",
    icon: Fingerprint,
    keywords: ["uuid", "guid", "v4", "identifier", "random"],
  },
  {
    slug: "url-encoder",
    name: "URL Encode/Decode",
    description: "Percent-encode and decode URL components.",
    category: "encoder",
    icon: Link2,
    keywords: ["url", "encode", "decode", "percent", "uri"],
  },
  {
    slug: "hash",
    name: "Hash Generator",
    description: "Compute MD5, SHA-1, SHA-256, and SHA-512 hashes.",
    category: "crypto",
    icon: Hash,
    keywords: ["hash", "md5", "sha1", "sha256", "sha512", "checksum"],
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JSON Web Tokens.",
    category: "encoder",
    icon: KeyRound,
    keywords: ["jwt", "json web token", "decode", "header", "payload"],
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    description: "Convert text between cases: camelCase, snake_case, kebab-case.",
    category: "text",
    icon: Type,
    keywords: ["case", "camel", "snake", "kebab", "pascal", "title", "upper", "lower"],
  },
  {
    slug: "qr-generator",
    name: "QR Code Generator",
    description: "Generate QR codes for URLs, text, Wi-Fi, and more.",
    category: "generator",
    icon: QrCode,
    keywords: ["qr", "code", "barcode", "url", "wifi"],
  },
  {
    slug: "color-picker",
    name: "Color Picker & Converter",
    description: "Pick colors and convert between HEX, RGB, HSL, OKLCH.",
    category: "color",
    icon: Palette,
    keywords: ["color", "hex", "rgb", "hsl", "oklch", "picker"],
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text by paragraphs, sentences, or words.",
    category: "generator",
    icon: FileText,
    keywords: ["lorem", "ipsum", "placeholder", "filler", "dummy"],
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    description: "Test JavaScript regex with live matches, groups, and replace.",
    category: "text",
    icon: Search,
    keywords: ["regex", "regexp", "pattern", "match", "test", "replace"],
    featured: true,
  },
  {
    slug: "html-entities",
    name: "HTML Entity Encoder",
    description: "Encode and decode HTML entities and named characters.",
    category: "encoder",
    icon: Code2,
    keywords: ["html", "entity", "escape", "unescape", "amp", "lt", "gt"],
  },
  {
    slug: "markdown-preview",
    name: "Markdown Preview",
    description: "Live preview Markdown with GitHub-flavored extensions.",
    category: "text",
    icon: FileCode2,
    keywords: ["markdown", "md", "preview", "gfm", "render"],
  },
  {
    slug: "diff-viewer",
    name: "Text Diff",
    description: "Compare two pieces of text and highlight line differences.",
    category: "text",
    icon: Diff,
    keywords: ["diff", "compare", "merge", "patch", "git"],
  },
  {
    slug: "word-counter",
    name: "Word & Char Counter",
    description: "Count words, characters, lines, and reading time.",
    category: "text",
    icon: BarChart3,
    keywords: ["count", "word", "character", "char", "lines", "reading"],
  },
  {
    slug: "text-sort",
    name: "Line Sorter & Dedup",
    description: "Sort, reverse, deduplicate, and shuffle lines of text.",
    category: "text",
    icon: ArrowDownAZ,
    keywords: ["sort", "lines", "deduplicate", "unique", "shuffle"],
  },
  {
    slug: "number-base",
    name: "Number Base Converter",
    description: "Convert numbers between binary, octal, decimal, and hex.",
    category: "converter",
    icon: Calculator,
    keywords: ["binary", "octal", "decimal", "hex", "base", "radix"],
  },
  {
    slug: "csv-to-json",
    name: "CSV ↔ JSON",
    description: "Convert CSV to JSON and back, with header detection.",
    category: "converter",
    icon: Table2,
    keywords: ["csv", "json", "tsv", "spreadsheet", "convert"],
  },
  {
    slug: "yaml-json",
    name: "YAML ↔ JSON",
    description: "Convert between YAML and JSON without leaving the browser.",
    category: "converter",
    icon: Boxes,
    keywords: ["yaml", "yml", "json", "convert", "config"],
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Generate strong passwords with custom rules and entropy.",
    category: "generator",
    icon: Key,
    keywords: ["password", "secret", "random", "entropy", "strong"],
  },
  {
    slug: "user-agent",
    name: "User Agent Parser",
    description: "Parse browser, OS, and device from a User-Agent string.",
    category: "web",
    icon: Globe,
    keywords: ["user agent", "ua", "browser", "device", "os"],
  },
  {
    slug: "contrast-checker",
    name: "Contrast Checker",
    description: "Check WCAG AA/AAA contrast ratios for any color pair.",
    category: "color",
    icon: Contrast,
    keywords: ["contrast", "wcag", "a11y", "accessibility", "ratio"],
  },
  {
    slug: "slugify",
    name: "Slugify",
    description: "Convert text to URL-safe slugs with diacritic stripping.",
    category: "text",
    icon: Tag,
    keywords: ["slug", "url", "kebab", "ascii", "unaccent"],
  },
  {
    slug: "html-formatter",
    name: "HTML Formatter",
    description: "Pretty-print and minify HTML documents.",
    category: "converter",
    icon: FileCode,
    keywords: ["html", "format", "pretty", "minify", "indent"],
  },
  {
    slug: "css-formatter",
    name: "CSS Formatter",
    description: "Format and minify CSS, SCSS, and LESS.",
    category: "converter",
    icon: FileType,
    keywords: ["css", "scss", "less", "format", "pretty", "minify"],
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    description: "Format SQL queries across multiple dialects.",
    category: "converter",
    icon: Database,
    keywords: ["sql", "format", "pretty", "mysql", "postgres", "query"],
  },
  {
    slug: "xml-json",
    name: "XML ↔ JSON",
    description: "Convert between XML and JSON in your browser.",
    category: "converter",
    icon: Brackets,
    keywords: ["xml", "json", "convert", "parser"],
  },
  {
    slug: "curl-converter",
    name: "cURL → fetch",
    description: "Convert cURL commands to JS fetch or Node.js syntax.",
    category: "web",
    icon: Terminal,
    keywords: ["curl", "fetch", "axios", "request", "convert"],
  },
  {
    slug: "cron-explainer",
    name: "Cron Explainer",
    description: "Explain and preview crontab expressions in plain English.",
    category: "time",
    icon: CalendarClock,
    keywords: ["cron", "crontab", "schedule", "explain"],
  },
  {
    slug: "cidr-calculator",
    name: "CIDR / Subnet Calc",
    description: "Calculate IPv4 subnets, ranges, and host counts.",
    category: "web",
    icon: Network,
    keywords: ["cidr", "subnet", "ip", "network", "mask"],
  },
  {
    slug: "jsonpath",
    name: "JSONPath Query",
    description: "Query JSON documents with JSONPath expressions.",
    category: "converter",
    icon: Filter,
    keywords: ["jsonpath", "query", "json", "filter", "extract"],
  },
  {
    slug: "image-base64",
    name: "Image → Base64",
    description: "Encode images to Base64 / data URIs and CSS snippets.",
    category: "encoder",
    icon: ImageIcon,
    keywords: ["image", "base64", "data uri", "embed", "css"],
  },
  {
    slug: "gradient-builder",
    name: "CSS Gradient Builder",
    description: "Build linear and radial gradients visually.",
    category: "color",
    icon: Wind,
    keywords: ["gradient", "linear", "radial", "css", "color"],
  },
  {
    slug: "box-shadow",
    name: "Box Shadow Builder",
    description: "Compose CSS box-shadow stacks visually.",
    category: "color",
    icon: Square,
    keywords: ["box shadow", "shadow", "css", "drop"],
  },
  {
    slug: "svg-formatter",
    name: "SVG Formatter",
    description: "Pretty-print, minify, and optimize SVG markup.",
    category: "converter",
    icon: Layers,
    keywords: ["svg", "format", "minify", "optimize"],
  },
  {
    slug: "mock-data",
    name: "Mock Data Generator",
    description: "Generate fake names, emails, addresses, and IDs.",
    category: "generator",
    icon: Dice5,
    keywords: ["mock", "fake", "faker", "data", "fixture"],
  },
  {
    slug: "totp",
    name: "TOTP Generator",
    description: "Generate RFC 6238 time-based one-time passwords.",
    category: "crypto",
    icon: ShieldCheck,
    keywords: ["totp", "otp", "2fa", "authenticator", "rfc6238"],
  },
  {
    slug: "string-escape",
    name: "String Escape",
    description: "Escape strings for JS, JSON, SQL, regex, or shell.",
    category: "encoder",
    icon: Quote,
    keywords: ["escape", "unescape", "string", "js", "json", "sql", "regex"],
  },
  {
    slug: "http-status",
    name: "HTTP Status Codes",
    description: "Look up HTTP status codes and their meanings.",
    category: "web",
    icon: ListChecks,
    keywords: ["http", "status", "code", "response", "rest"],
  },
  {
    slug: "mermaid",
    name: "Mermaid Live",
    description: "Render Mermaid diagrams: flowcharts, sequence, gantt, ER, more.",
    category: "converter",
    icon: Workflow,
    keywords: ["mermaid", "diagram", "flowchart", "sequence", "gantt", "graph"],
    featured: true,
  },
  {
    slug: "db-diagram",
    name: "DB Diagram",
    description: "Visualize database schemas from DBML — like dbdiagram.io.",
    category: "converter",
    icon: TableProperties,
    keywords: ["dbml", "database", "schema", "er", "erd", "dbdiagram"],
    featured: true,
  },
  {
    slug: "diagram",
    name: "Diagram Editor",
    description: "Visual diagram editor with BPMN, flowchart, and UML shapes — like draw.io.",
    category: "converter",
    icon: Shapes,
    keywords: [
      "diagram",
      "drawio",
      "draw.io",
      "bpmn",
      "flowchart",
      "uml",
      "shapes",
      "process",
      "workflow",
      "swimlane",
    ],
    featured: true,
  },
  {
    slug: "timezone-converter",
    name: "Timezone Converter",
    description: "Convert a date and time between any two timezones instantly.",
    category: "time",
    icon: Globe2,
    keywords: ["timezone", "time zone", "convert", "utc", "dst", "world clock"],
  },
  {
    slug: "chmod-calculator",
    name: "Chmod Calculator",
    description: "Calculate Unix file permissions with a visual checkbox grid.",
    category: "web",
    icon: Lock,
    keywords: ["chmod", "permissions", "unix", "linux", "octal", "rwx"],
  },
  {
    slug: "json-schema-validator",
    name: "JSON Schema Validator",
    description: "Validate a JSON document against a JSON Schema (draft-07 subset).",
    category: "converter",
    icon: FileCheck,
    keywords: ["json schema", "validate", "jsonschema", "draft-07", "lint"],
  },
  {
    slug: "byte-converter",
    name: "Byte / Size Converter",
    description: "Convert between bits, bytes, KB, MB, GB, TB and their binary (KiB, MiB…) equivalents.",
    category: "converter",
    icon: HardDrive,
    keywords: ["byte", "kilobyte", "megabyte", "gigabyte", "kib", "mib", "size", "convert"],
  },
  {
    slug: "color-palette",
    name: "Color Palette Generator",
    description: "Generate harmonious color palettes using complementary, triadic, analogous, and more.",
    category: "color",
    icon: Paintbrush,
    keywords: ["color", "palette", "harmony", "complementary", "triadic", "analogous", "generator"],
  },
  {
    slug: "json-to-typescript",
    name: "JSON → TypeScript",
    description: "Generate TypeScript interfaces and types from a JSON object.",
    category: "converter",
    icon: FileJson,
    keywords: ["json", "typescript", "interface", "type", "generate", "convert"],
  },
  {
    slug: "jwt-builder",
    name: "JWT Builder",
    description: "Build and sign JSON Web Tokens with HS256 using the Web Crypto API.",
    category: "encoder",
    icon: Shield,
    keywords: ["jwt", "json web token", "sign", "hs256", "hmac", "build"],
  },
  {
    slug: "semver-calculator",
    name: "Semver Calculator",
    description: "Parse, compare, increment, and check range satisfaction for semantic versions.",
    category: "web",
    icon: GitBranch,
    keywords: ["semver", "semantic version", "compare", "range", "npm", "increment"],
  },
  {
    slug: "gitignore-generator",
    name: ".gitignore Generator",
    description: "Generate .gitignore files for any combination of languages, frameworks, and IDEs.",
    category: "generator",
    icon: FileX,
    keywords: ["gitignore", "git", "ignore", "node", "python", "rust", "go"],
  },
  {
    slug: "url-parser",
    name: "URL Parser",
    description: "Break down a URL into its components and edit query parameters interactively.",
    category: "web",
    icon: Link,
    keywords: ["url", "parse", "query", "params", "hostname", "pathname", "hash"],
  },
  {
    slug: "date-calculator",
    name: "Date Calculator",
    description: "Calculate the difference between dates, add/subtract durations, and count workdays.",
    category: "time",
    icon: CalendarDays,
    keywords: ["date", "calculator", "difference", "workdays", "add", "subtract", "duration"],
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    description: "Convert between units of length, weight, temperature, speed, area, volume, and data.",
    category: "converter",
    icon: Ruler,
    keywords: ["unit", "convert", "length", "weight", "temperature", "speed", "area", "volume"],
  },
  {
    slug: "toml-json",
    name: "TOML ↔ JSON",
    description: "Convert between TOML and JSON — great for Cargo.toml, Hugo config, and more.",
    category: "converter",
    icon: Boxes,
    keywords: ["toml", "json", "convert", "cargo", "hugo", "config"],
  },
];

export function getTool(slug: string): Tool | undefined {
  return tools.find((tool) => tool.slug === slug);
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return tools.filter((tool) => tool.category === category);
}

export function getFeaturedTools(): Tool[] {
  return tools.filter((tool) => tool.featured);
}
