import type { LucideIcon } from "lucide-react";
import {
  Braces,
  FileText,
  Clock,
  Hash,
  KeyRound,
  Link2,
  Palette,
  QrCode,
  Type,
  Binary,
  Fingerprint,
  Search,
  Code2,
  Tag,
  BarChart3,
  ArrowDownAZ,
  Calculator,
  Table2,
  Diff,
  Key,
  Boxes,
  Globe,
  Contrast,
  FileCode2,
  FileCode,
  Database,
  FileType,
  Brackets,
  Terminal,
  CalendarClock,
  Network,
  Filter,
  Image as ImageIcon,
  Wind,
  Layers,
  Square,
  Dice5,
  ShieldCheck,
  Quote,
  ListChecks,
  Workflow,
  TableProperties,
  Shapes,
  Paintbrush,
  Globe2,
  FileCheck,
  HardDrive,
  Lock,
  FileJson,
  Shield,
  GitBranch,
  FileX,
  Link,
  CalendarDays,
  Ruler,
  Share2,
  CheckCircle,
  Timer,
  KeySquare,
  LockKeyhole,
  FileSearch,
  MousePointer2,
  BoxSelect,
  BookOpen,
  Server,
  Award,
  FileScan,
  Container,
  FileWarning,
  DatabaseZap,
  TableCellsMerge,
  LayoutGrid,
  PenTool,
  Cpu,
  Radio,
  Bot,
  ScanLine,
  SlidersHorizontal,
  Milestone,
} from "lucide-react";

export type ToolCategory =
  | "converter"
  | "encoder"
  | "generator"
  | "text"
  | "time"
  | "web"
  | "color"
  | "crypto";

export interface Tool {
  slug: string;
  name: string;
  description: string;
  category: ToolCategory;
  icon: LucideIcon;
  keywords: string[];
  featured?: boolean;
}

export interface CategoryMeta {
  id: ToolCategory;
  label: string;
  description: string;
}

export const categories: CategoryMeta[] = [
  { id: "converter", label: "Converter", description: "Convert between formats and units" },
  { id: "encoder", label: "Encoder", description: "Encode, decode, and transform data" },
  { id: "generator", label: "Generator", description: "Generate IDs, codes, and mock data" },
  { id: "text", label: "Text", description: "Manipulate and analyze text" },
  { id: "time", label: "Time", description: "Work with timestamps and dates" },
  { id: "web", label: "Web", description: "Tools for the web" },
  { id: "color", label: "Color", description: "Pick, convert, and explore colors" },
  { id: "crypto", label: "Crypto", description: "Hashes and cryptographic primitives" },
];

export const tools: Tool[] = [
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Format, minify, and validate JSON instantly in your browser.",
    category: "converter",
    icon: Braces,
    keywords: ["json", "format", "pretty", "minify", "validate", "lint"],
    featured: true,
  },
  {
    slug: "json-diff",
    name: "JSON Diff",
    description: "Compare two JSON objects and highlight added, removed, and changed fields.",
    category: "converter",
    icon: Diff,
    keywords: ["json", "diff", "compare", "delta", "patch", "merge", "changes"],
  },
  {
    slug: "base64",
    name: "Base64 Encode/Decode",
    description: "Convert text to and from Base64 with one click.",
    category: "encoder",
    icon: Binary,
    keywords: ["base64", "encode", "decode", "atob", "btoa"],
    featured: true,
  },
  {
    slug: "unix-timestamp",
    name: "Unix Timestamp Converter",
    description: "Convert between Unix timestamps and human-readable dates.",
    category: "time",
    icon: Clock,
    keywords: ["unix", "timestamp", "epoch", "date", "iso", "time"],
    featured: true,
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate UUID v4 identifiers in bulk.",
    category: "generator",
    icon: Fingerprint,
    keywords: ["uuid", "guid", "v4", "identifier", "random"],
  },
  {
    slug: "url-encoder",
    name: "URL Encode/Decode",
    description: "Percent-encode and decode URL components.",
    category: "encoder",
    icon: Link2,
    keywords: ["url", "encode", "decode", "percent", "uri"],
  },
  {
    slug: "hash",
    name: "Hash Generator",
    description: "Compute MD5, SHA-1, SHA-256, and SHA-512 hashes.",
    category: "crypto",
    icon: Hash,
    keywords: ["hash", "md5", "sha1", "sha256", "sha512", "checksum"],
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JSON Web Tokens.",
    category: "encoder",
    icon: KeyRound,
    keywords: ["jwt", "json web token", "decode", "header", "payload"],
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    description: "Convert text between cases: camelCase, snake_case, kebab-case.",
    category: "text",
    icon: Type,
    keywords: ["case", "camel", "snake", "kebab", "pascal", "title", "upper", "lower"],
  },
  {
    slug: "qr-generator",
    name: "QR Code Generator",
    description: "Generate QR codes for URLs, text, Wi-Fi, and more.",
    category: "generator",
    icon: QrCode,
    keywords: ["qr", "code", "barcode", "url", "wifi"],
  },
  {
    slug: "color-picker",
    name: "Color Picker & Converter",
    description: "Pick colors and convert between HEX, RGB, HSL, OKLCH.",
    category: "color",
    icon: Palette,
    keywords: ["color", "hex", "rgb", "hsl", "oklch", "picker"],
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text by paragraphs, sentences, or words.",
    category: "generator",
    icon: FileText,
    keywords: ["lorem", "ipsum", "placeholder", "filler", "dummy"],
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    description: "Test JavaScript regex with live matches, groups, and replace.",
    category: "text",
    icon: Search,
    keywords: ["regex", "regexp", "pattern", "match", "test", "replace"],
    featured: true,
  },
  {
    slug: "html-entities",
    name: "HTML Entity Encoder",
    description: "Encode and decode HTML entities and named characters.",
    category: "encoder",
    icon: Code2,
    keywords: ["html", "entity", "escape", "unescape", "amp", "lt", "gt"],
  },
  {
    slug: "markdown-preview",
    name: "Markdown Preview",
    description: "Live preview Markdown with GitHub-flavored extensions.",
    category: "text",
    icon: FileCode2,
    keywords: ["markdown", "md", "preview", "gfm", "render"],
  },
  {
    slug: "diff-viewer",
    name: "Text Diff",
    description: "Compare two pieces of text and highlight line differences.",
    category: "text",
    icon: Diff,
    keywords: ["diff", "compare", "merge", "patch", "git"],
  },
  {
    slug: "word-counter",
    name: "Word & Char Counter",
    description: "Count words, characters, lines, and reading time.",
    category: "text",
    icon: BarChart3,
    keywords: ["count", "word", "character", "char", "lines", "reading"],
  },
  {
    slug: "text-sort",
    name: "Line Sorter & Dedup",
    description: "Sort, reverse, deduplicate, and shuffle lines of text.",
    category: "text",
    icon: ArrowDownAZ,
    keywords: ["sort", "lines", "deduplicate", "unique", "shuffle"],
  },
  {
    slug: "number-base",
    name: "Number Base Converter",
    description: "Convert numbers between binary, octal, decimal, and hex.",
    category: "converter",
    icon: Calculator,
    keywords: ["binary", "octal", "decimal", "hex", "base", "radix"],
  },
  {
    slug: "csv-to-json",
    name: "CSV ↔ JSON",
    description: "Convert CSV to JSON and back, with header detection.",
    category: "converter",
    icon: Table2,
    keywords: ["csv", "json", "tsv", "spreadsheet", "convert"],
  },
  {
    slug: "yaml-json",
    name: "YAML ↔ JSON",
    description: "Convert between YAML and JSON without leaving the browser.",
    category: "converter",
    icon: Boxes,
    keywords: ["yaml", "yml", "json", "convert", "config"],
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Generate strong passwords with custom rules and entropy.",
    category: "generator",
    icon: Key,
    keywords: ["password", "secret", "random", "entropy", "strong"],
  },
  {
    slug: "user-agent",
    name: "User Agent Parser",
    description: "Parse browser, OS, and device from a User-Agent string.",
    category: "web",
    icon: Globe,
    keywords: ["user agent", "ua", "browser", "device", "os"],
  },
  {
    slug: "contrast-checker",
    name: "Contrast Checker",
    description: "Check WCAG AA/AAA contrast ratios for any color pair.",
    category: "color",
    icon: Contrast,
    keywords: ["contrast", "wcag", "a11y", "accessibility", "ratio"],
  },
  {
    slug: "slugify",
    name: "Slugify",
    description: "Convert text to URL-safe slugs with diacritic stripping.",
    category: "text",
    icon: Tag,
    keywords: ["slug", "url", "kebab", "ascii", "unaccent"],
  },
  {
    slug: "html-formatter",
    name: "HTML Formatter",
    description: "Pretty-print and minify HTML documents.",
    category: "converter",
    icon: FileCode,
    keywords: ["html", "format", "pretty", "minify", "indent"],
  },
  {
    slug: "css-formatter",
    name: "CSS Formatter",
    description: "Format and minify CSS, SCSS, and LESS.",
    category: "converter",
    icon: FileType,
    keywords: ["css", "scss", "less", "format", "pretty", "minify"],
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    description: "Format SQL queries across multiple dialects.",
    category: "converter",
    icon: Database,
    keywords: ["sql", "format", "pretty", "mysql", "postgres", "query"],
  },
  {
    slug: "xml-json",
    name: "XML ↔ JSON",
    description: "Convert between XML and JSON in your browser.",
    category: "converter",
    icon: Brackets,
    keywords: ["xml", "json", "convert", "parser"],
  },
  {
    slug: "curl-converter",
    name: "cURL → fetch",
    description: "Convert cURL commands to JS fetch or Node.js syntax.",
    category: "web",
    icon: Terminal,
    keywords: ["curl", "fetch", "axios", "request", "convert"],
  },
  {
    slug: "cron-explainer",
    name: "Cron Explainer",
    description: "Explain and preview crontab expressions in plain English.",
    category: "time",
    icon: CalendarClock,
    keywords: ["cron", "crontab", "schedule", "explain"],
  },
  {
    slug: "cidr-calculator",
    name: "CIDR / Subnet Calc",
    description: "Calculate IPv4 subnets, ranges, and host counts.",
    category: "web",
    icon: Network,
    keywords: ["cidr", "subnet", "ip", "network", "mask"],
  },
  {
    slug: "jsonpath",
    name: "JSONPath Query",
    description: "Query JSON documents with JSONPath expressions.",
    category: "converter",
    icon: Filter,
    keywords: ["jsonpath", "query", "json", "filter", "extract"],
  },
  {
    slug: "json-query",
    name: "JSON Query (JMESPath)",
    description: "Query JSON with JMESPath — filters, projections, functions, and key autocomplete.",
    category: "converter",
    icon: FileSearch,
    keywords: ["json", "query", "jmespath", "filter", "autocomplete", "search", "projection"],
    featured: true,
  },
  {
    slug: "image-base64",
    name: "Image → Base64",
    description: "Encode images to Base64 / data URIs and CSS snippets.",
    category: "encoder",
    icon: ImageIcon,
    keywords: ["image", "base64", "data uri", "embed", "css"],
  },
  {
    slug: "gradient-builder",
    name: "CSS Gradient Builder",
    description: "Build linear and radial gradients visually.",
    category: "color",
    icon: Wind,
    keywords: ["gradient", "linear", "radial", "css", "color"],
  },
  {
    slug: "box-shadow",
    name: "Box Shadow Builder",
    description: "Compose CSS box-shadow stacks visually.",
    category: "color",
    icon: Square,
    keywords: ["box shadow", "shadow", "css", "drop"],
  },
  {
    slug: "svg-formatter",
    name: "SVG Formatter",
    description: "Pretty-print, minify, and optimize SVG markup.",
    category: "converter",
    icon: Layers,
    keywords: ["svg", "format", "minify", "optimize"],
  },
  {
    slug: "mock-data",
    name: "Mock Data Generator",
    description: "Generate fake names, emails, addresses, and IDs.",
    category: "generator",
    icon: Dice5,
    keywords: ["mock", "fake", "faker", "data", "fixture"],
  },
  {
    slug: "totp",
    name: "TOTP Generator",
    description: "Generate RFC 6238 time-based one-time passwords.",
    category: "crypto",
    icon: ShieldCheck,
    keywords: ["totp", "otp", "2fa", "authenticator", "rfc6238"],
  },
  {
    slug: "string-escape",
    name: "String Escape",
    description: "Escape strings for JS, JSON, SQL, regex, or shell.",
    category: "encoder",
    icon: Quote,
    keywords: ["escape", "unescape", "string", "js", "json", "sql", "regex"],
  },
  {
    slug: "http-status",
    name: "HTTP Status Codes",
    description: "Look up HTTP status codes and their meanings.",
    category: "web",
    icon: ListChecks,
    keywords: ["http", "status", "code", "response", "rest"],
  },
  {
    slug: "mermaid",
    name: "Mermaid Live",
    description: "Render Mermaid diagrams: flowcharts, sequence, gantt, ER, more.",
    category: "converter",
    icon: Workflow,
    keywords: ["mermaid", "diagram", "flowchart", "sequence", "gantt", "graph"],
    featured: true,
  },
  {
    slug: "db-diagram",
    name: "DB Diagram",
    description: "Visualize database schemas from DBML — like dbdiagram.io.",
    category: "converter",
    icon: TableProperties,
    keywords: ["dbml", "database", "schema", "er", "erd", "dbdiagram"],
    featured: true,
  },
  {
    slug: "diagram",
    name: "Diagram Editor",
    description: "Visual diagram editor with BPMN, flowchart, and UML shapes — like draw.io.",
    category: "converter",
    icon: Shapes,
    keywords: [
      "diagram",
      "drawio",
      "draw.io",
      "bpmn",
      "flowchart",
      "uml",
      "shapes",
      "process",
      "workflow",
      "swimlane",
    ],
    featured: true,
  },
  {
    slug: "timezone-converter",
    name: "Timezone Converter",
    description: "Convert a date and time between any two timezones instantly.",
    category: "time",
    icon: Globe2,
    keywords: ["timezone", "time zone", "convert", "utc", "dst", "world clock"],
  },
  {
    slug: "chmod-calculator",
    name: "Chmod Calculator",
    description: "Calculate Unix file permissions with a visual checkbox grid.",
    category: "web",
    icon: Lock,
    keywords: ["chmod", "permissions", "unix", "linux", "octal", "rwx"],
  },
  {
    slug: "json-schema-validator",
    name: "JSON Schema Validator",
    description: "Validate a JSON document against a JSON Schema (draft-07 subset).",
    category: "converter",
    icon: FileCheck,
    keywords: ["json schema", "validate", "jsonschema", "draft-07", "lint"],
  },
  {
    slug: "byte-converter",
    name: "Byte / Size Converter",
    description: "Convert between bits, bytes, KB, MB, GB, TB and their binary (KiB, MiB…) equivalents.",
    category: "converter",
    icon: HardDrive,
    keywords: ["byte", "kilobyte", "megabyte", "gigabyte", "kib", "mib", "size", "convert"],
  },
  {
    slug: "color-palette",
    name: "Color Palette Generator",
    description: "Generate harmonious color palettes using complementary, triadic, analogous, and more.",
    category: "color",
    icon: Paintbrush,
    keywords: ["color", "palette", "harmony", "complementary", "triadic", "analogous", "generator"],
  },
  {
    slug: "json-to-typescript",
    name: "JSON → TypeScript",
    description: "Generate TypeScript interfaces and types from a JSON object.",
    category: "converter",
    icon: FileJson,
    keywords: ["json", "typescript", "interface", "type", "generate", "convert"],
  },
  {
    slug: "jwt-builder",
    name: "JWT Builder",
    description: "Build and sign JSON Web Tokens with HS256 using the Web Crypto API.",
    category: "encoder",
    icon: Shield,
    keywords: ["jwt", "json web token", "sign", "hs256", "hmac", "build"],
  },
  {
    slug: "semver-calculator",
    name: "Semver Calculator",
    description: "Parse, compare, increment, and check range satisfaction for semantic versions.",
    category: "web",
    icon: GitBranch,
    keywords: ["semver", "semantic version", "compare", "range", "npm", "increment"],
  },
  {
    slug: "gitignore-generator",
    name: ".gitignore Generator",
    description: "Generate .gitignore files for any combination of languages, frameworks, and IDEs.",
    category: "generator",
    icon: FileX,
    keywords: ["gitignore", "git", "ignore", "node", "python", "rust", "go"],
  },
  {
    slug: "url-parser",
    name: "URL Parser",
    description: "Break down a URL into its components and edit query parameters interactively.",
    category: "web",
    icon: Link,
    keywords: ["url", "parse", "query", "params", "hostname", "pathname", "hash"],
  },
  {
    slug: "date-calculator",
    name: "Date Calculator",
    description: "Calculate the difference between dates, add/subtract durations, and count workdays.",
    category: "time",
    icon: CalendarDays,
    keywords: ["date", "calculator", "difference", "workdays", "add", "subtract", "duration"],
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    description: "Convert between units of length, weight, temperature, speed, area, volume, and data.",
    category: "converter",
    icon: Ruler,
    keywords: ["unit", "convert", "length", "weight", "temperature", "speed", "area", "volume"],
  },
  {
    slug: "toml-json",
    name: "TOML ↔ JSON",
    description: "Convert between TOML and JSON — great for Cargo.toml, Hugo config, and more.",
    category: "converter",
    icon: Boxes,
    keywords: ["toml", "json", "convert", "cargo", "hugo", "config"],
  },
  {
    slug: "paste-share",
    name: "Paste & Share",
    description: "Paste content and get a shareable link — stored for 7 days.",
    category: "web",
    icon: Share2,
    keywords: ["paste", "share", "link", "snippet", "gist"],
  },
  // Temporarily hidden: URL-fragment paste produces very long URLs for large
  // content (inherent to the zero-server design). Files kept; re-enable here
  // when a short-URL approach (e.g. zero-knowledge server) is decided.
  // {
  //   slug: "url-paste",
  //   name: "URL Paste",
  //   description: "Compress content into a shareable link — fully local, nothing hits a server. The offline counterpart to Paste & Share.",
  //   category: "web",
  //   icon: Link2,
  //   keywords: ["paste", "share", "url", "local", "offline", "compress", "fragment", "private", "encrypt"],
  // },
  {
    slug: "cron-builder",
    name: "Cron Builder",
    description: "Build cron expressions visually — click to set schedule, preview next runs.",
    category: "time",
    icon: Timer,
    keywords: ["cron", "schedule", "builder", "visual", "job", "task"],
  },
  {
    slug: "env-diff",
    name: "Env Diff",
    description: "Compare two .env files — highlight missing, changed, and added keys.",
    category: "text",
    icon: FileSearch,
    keywords: ["env", "diff", "compare", "environment", "variables", "dotenv"],
  },
  {
    slug: "sql-playground",
    name: "SQL Playground",
    description: "Run SQL queries in the browser with SQLite WASM — no server needed.",
    category: "converter",
    icon: Database,
    keywords: ["sql", "sqlite", "query", "database", "playground", "wasm"],
  },
  {
    slug: "regex-builder",
    name: "Regex Builder",
    description: "Build regular expressions visually with explanations for each part.",
    category: "text",
    icon: MousePointer2,
    keywords: ["regex", "builder", "visual", "pattern", "regular expression"],
  },
  {
    slug: "ascii-box-drawing",
    name: "ASCII Box Drawing",
    description: "Draw box diagrams with text characters — perfect for READMEs and comments.",
    category: "text",
    icon: BoxSelect,
    keywords: ["ascii", "box", "drawing", "diagram", "text", "art"],
  },
  {
    slug: "openapi-viewer",
    name: "OpenAPI Viewer",
    description: "Paste OpenAPI/Swagger spec and get interactive API documentation.",
    category: "web",
    icon: BookOpen,
    keywords: ["openapi", "swagger", "api", "docs", "spec", "rest"],
  },
  {
    slug: "ssh-config-generator",
    name: "SSH Config Generator",
    description: "Generate ~/.ssh/config entries with a form — no syntax memorization needed.",
    category: "web",
    icon: Server,
    keywords: ["ssh", "config", "generator", "remote", "server", "key"],
  },
  {
    slug: "asn1-decoder",
    name: "ASN.1 Decoder",
    description: "Decode ASN.1 DER/PEM structures — view the TLV tree with OID lookup.",
    category: "crypto",
    icon: FileSearch,
    keywords: ["asn1", "der", "pem", "decode", "certificate", "tlv", "oid"],
  },
  {
    slug: "certificate-decoder",
    name: "Certificate Decoder",
    description: "Decode X.509 PEM certificates — view issuer, expiry, SANs, and chain.",
    category: "crypto",
    icon: Award,
    keywords: ["certificate", "x509", "pem", "ssl", "tls", "decode", "san"],
  },
  {
    slug: "ulid-nanoid-generator",
    name: "ULID & NanoID Generator",
    description: "Generate ULIDs, NanoIDs, and other alternative ID formats.",
    category: "generator",
    icon: Fingerprint,
    keywords: ["ulid", "nanoid", "id", "generator", "unique", "sortable"],
  },
  {
    slug: "checksum-verifier",
    name: "Checksum Verifier",
    description: "Calculate MD5, SHA-1, SHA-256 checksums for files — drag and drop.",
    category: "crypto",
    icon: FileScan,
    keywords: ["checksum", "md5", "sha", "hash", "verify", "file", "integrity"],
  },
  {
    slug: "dockerfile-linter",
    name: "Dockerfile Linter",
    description: "Lint Dockerfiles against best practices — catch common mistakes.",
    category: "web",
    icon: Container,
    keywords: ["docker", "dockerfile", "lint", "container", "best practices"],
  },
  {
    slug: "yaml-validator",
    name: "YAML Validator",
    description: "Validate YAML syntax with helpful error messages and line highlighting.",
    category: "converter",
    icon: FileWarning,
    keywords: ["yaml", "validate", "syntax", "check", "kubernetes", "ci"],
  },
  {
    slug: "dns-record-builder",
    name: "DNS Record Builder",
    description: "Build DNS zone file records from a simple form — A, AAAA, CNAME, MX, TXT.",
    category: "web",
    icon: Globe2,
    keywords: ["dns", "record", "zone", "builder", "domain", "nameserver"],
  },
  {
    slug: "json-to-sql",
    name: "JSON → SQL INSERT",
    description: "Convert JSON arrays to SQL INSERT statements — supports multiple dialects.",
    category: "converter",
    icon: DatabaseZap,
    keywords: ["json", "sql", "insert", "convert", "migration", "data"],
  },
  {
    slug: "markdown-table-generator",
    name: "Markdown Table Generator",
    description: "Visual table editor that exports clean Markdown tables.",
    category: "text",
    icon: TableCellsMerge,
    keywords: ["markdown", "table", "generator", "editor", "github"],
  },
  {
    slug: "text-to-ascii-table",
    name: "Text → ASCII Table",
    description: "Convert CSV or TSV data into formatted ASCII tables.",
    category: "text",
    icon: LayoutGrid,
    keywords: ["ascii", "table", "csv", "tsv", "format", "text"],
  },
  {
    slug: "diagram-dsl",
    name: "Diagram DSL",
    description: "Draw diagrams with a simple DSL — like eraser.io. Flowcharts, sequence, ERD, and more.",
    category: "converter",
    icon: PenTool,
    keywords: [
      "diagram",
      "dsl",
      "eraser",
      "flowchart",
      "sequence",
      "erd",
      "class",
      "gantt",
      "state",
      "pie",
      "mindmap",
      "code",
    ],
    featured: true,
  },
  {
    slug: "hex-encode",
    name: "Hex Encode/Decode",
    description: "Convert text to/from hexadecimal string.",
    category: "encoder",
    icon: Binary,
    keywords: ["hex", "encode", "decode", "hexadecimal", "binary"],
  },
  {
    slug: "binary-text",
    name: "Binary Text Converter",
    description: "Convert text to/from binary (01010100…).",
    category: "encoder",
    icon: Cpu,
    keywords: ["binary", "text", "convert", "bits", "01"],
  },
  {
    slug: "morse-code",
    name: "Morse Code Encoder/Decoder",
    description: "Encode and decode Morse code (dots and dashes).",
    category: "encoder",
    icon: Radio,
    keywords: ["morse", "code", "dot", "dash", "encode", "decode"],
  },
  {
    slug: "punycode",
    name: "Punycode Encoder/Decoder",
    description: "Convert internationalized domain names to/from ASCII Punycode.",
    category: "encoder",
    icon: Globe2,
    keywords: ["punycode", "idn", "internationalized", "domain", "ascii", "unicode"],
  },
  {
    slug: "uri-component",
    name: "URI Component Encoder/Decoder",
    description: "Encode/decode URI components with encodeURIComponent vs encodeURI.",
    category: "encoder",
    icon: Link,
    keywords: ["uri", "url", "encode", "decode", "component", "percent"],
  },
  {
    slug: "cuid-generator",
    name: "CUID2 / CUID Generator",
    description: "Generate CUID2 and CUID collision-resistant unique identifiers.",
    category: "generator",
    icon: Fingerprint,
    keywords: ["cuid", "cuid2", "id", "generator", "unique", "collision", "resistant"],
  },
  {
    slug: "robots-txt-validator",
    name: "robots.txt Validator",
    description: "Validate robots.txt syntax and test URL matching against rules.",
    category: "web",
    icon: Bot,
    keywords: ["robots", "txt", "seo", "crawl", "bot", "validate", "disallow"],
  },
  {
    slug: "jwk-inspector",
    name: "JSON Web Key (JWK) Inspector",
    description: "Decode and inspect JWK and JWKS (JSON Web Key Set) objects.",
    category: "crypto",
    icon: Key,
    keywords: ["jwk", "jwks", "json web key", "rsa", "ec", "public key", "inspect"],
  },
  {
    slug: "otp-secret-generator",
    name: "OTP Secret Generator",
    description: "Generate TOTP/HOTP secrets and QR codes for authenticator apps.",
    category: "generator",
    icon: ScanLine,
    keywords: ["otp", "totp", "hotp", "2fa", "secret", "qr", "authenticator", "mfa"],
  },
  {
    slug: "hmac-generator",
    name: "HMAC Generator",
    description: "Compute HMAC-SHA256/SHA512 with a secret key for webhook signature verification.",
    category: "crypto",
    icon: KeySquare,
    keywords: ["hmac", "sha256", "sha512", "signature", "webhook", "secret", "mac"],
  },
  {
    slug: "bcrypt-hash",
    name: "Bcrypt Hash",
    description: "Hash and verify passwords with bcrypt entirely in the browser.",
    category: "crypto",
    icon: LockKeyhole,
    keywords: ["bcrypt", "hash", "password", "verify", "salt", "rounds"],
  },
  {
    slug: "aes-encrypt",
    name: "AES Encrypt / Decrypt",
    description: "Client-side AES-256-GCM encryption and decryption of text.",
    category: "crypto",
    icon: ShieldCheck,
    keywords: ["aes", "encrypt", "decrypt", "aes-256", "gcm", "symmetric", "cipher"],
  },
  {
    slug: "ini-json",
    name: "INI ↔ JSON Converter",
    description: "Convert Windows-style INI config files to JSON and back.",
    category: "converter",
    icon: SlidersHorizontal,
    keywords: ["ini", "json", "config", "convert", "windows", "section", "property"],
  },
  {
    slug: "roman-numeral",
    name: "Roman Numeral Converter",
    description: "Convert between Arabic and Roman numerals (1–3999).",
    category: "converter",
    icon: Milestone,
    keywords: ["roman", "numeral", "arabic", "convert", "number", "i", "v", "x"],
  },
  {
    slug: "ipv4-ipv6",
    name: "IPv4 / IPv6 Converter",
    description: "Convert between IPv4 and IPv6 representations, check address type and range.",
    category: "web",
    icon: Network,
    keywords: ["ipv4", "ipv6", "ip", "convert", "network", "address", "cidr"],
  },
  {
    slug: "unicode-inspector",
    name: "Unicode Inspector",
    description: "Show Unicode codepoints, hex escapes, HTML entities, and UTF-8 bytes for each character.",
    category: "text",
    icon: Type,
    keywords: ["unicode", "codepoint", "character", "utf8", "utf16", "inspect", "encode"],
  },
  {
    slug: "mime-lookup",
    name: "MIME Type Lookup",
    description: "Look up MIME types by file extension, or find extensions for a given MIME type.",
    category: "web",
    icon: FileType,
    keywords: ["mime", "type", "extension", "content-type", "file", "media"],
  },
  {
    slug: "http-header-analyzer",
    name: "HTTP Header Analyzer",
    description: "Paste raw HTTP headers and get a parsed, categorized breakdown with explanations.",
    category: "web",
    icon: Server,
    keywords: ["http", "header", "analyze", "parse", "request", "response", "curl"],
  },
];

export function getTool(slug: string): Tool | undefined {
  return tools.find((tool) => tool.slug === slug);
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return tools.filter((tool) => tool.category === category);
}

export function getFeaturedTools(): Tool[] {
  return tools.filter((tool) => tool.featured);
}
