---
import ToolLayout from "@/layouts/tool-layout.astro";
import DockerfileLinterTool from "@/components/tools/dockerfile-linter-tool.tsx";
---

<ToolLayout slug="dockerfile-linter">
  <DockerfileLinterTool client:load />
</ToolLayout>
